name: Create Release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Bake
        uses: docker/bake-action@v6
        with:
          targets: all

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha }}
          body: "Automated release of UKIs"
          files: |
            images/*.efi
            images/linux_amd64/*.efi
            images/linux_arm64/*.efi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
